# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YlZg4kbU1WCurp5E3-OLGg34oIa5SWWR
"""

import pandas as pd

# Create a reservation DataFrame

df = pd.DataFrame()
# Add columns to df

df['reservation_id'] = []
df['employee_id'] = []
df['building_id'] = []
df['date'] = []
df['seat_id'] = []

df = pd.DataFrame(columns=["reservation_id", "employee_id", "building_id", "seat_id", "date"], dtype=object)
df['date'] = pd.to_datetime(df['date'])

# Save the dataframe
df.to_csv('reservation_data.csv', index=False)

def load_reservation_dataframe():
  df = pd.read_csv('reservation_data.csv')

  return df
# Create new reservation entry

def add_reservation(employee_id, building_id, seat_id, date, df):

  # Assign value to reservation_id
  if 'reservation_id' in df.columns and not df['reservation_id'].empty:
    reservation_id = df['reservation_id'].max()
  else:
    reservation_id = 0 # When there are no reservations

  new_reservation = {"reservation_id" : reservation_id + 1, "employee_id" : employee_id, "building_id" : building_id, "seat_id" : seat_id, "date" : date}
  df = df.append(new_reservation, ignore_index=True)
  print("New reservation for " + str(date) + " in building " + str(building_id) + " added.")

  df.to_csv('reservation_data.csv', index=False)

  return df

def check_empty(seat_id, date):

    import streamlit as st

# Title
st.title("Simple Streamlit App")

# Text input field
user_input = st.text_input("Enter something:")

# Display the user's input
st.write(f"You entered: {user_input}")


